SELECT A.FLAVOR
FROM FIRST_HALF A INNER JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL
                              FROM JULY
                              GROUP BY FLAVOR) J ON A.FLAVOR = J.FLAVOR
 ORDER BY A.TOTAL_ORDER + J.JULY_TOTAL DESC
 LIMIT 3