-- 코드를 입력하세요

WITH RECURSIVE TIME AS (
    SELECT 0 AS TIME_HOUR
    UNION ALL
    SELECT TIME_HOUR + 1 FROM TIME
    WHERE TIME_HOUR < 23 )

SELECT TIME.TIME_HOUR, COUNT(HOUR(DATETIME)) AS COUNT
FROM ANIMAL_OUTS RIGHT JOIN TIME ON HOUR(DATETIME) = TIME.TIME_HOUR
GROUP BY TIME.TIME_HOUR
ORDER BY TIME.TIME_HOUR